version: '3'

services:
  db:
    image: postgis/postgis
    container_name: postgis
    volumes: 
      - ${DATA_PATH}:/var/lib/postgresql/data
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - ALLOW_IP_RANGE=0.0.0.0/0
    networks:
      - my_network
    ports:
      - "2222:${DB_PORT}"
  auth:
    image: auth_server/Dockerfile
    container_name: auth_server
    depends_on:
      - db
    networks:
      - my_network
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_SERVER=localhost
      - DB_PORT=5432
      - DB_NAME=servico_autenticacao
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=3010
      - DB_CREATE=true
      - AUTH_USER=admin
      - AUTH_PASSWORD=admin
      - DATA_PATH=.

networks:
  my_network: